"""Cross-process contracts shared by the Portal API and Root Worker."""

from h100_portal_contracts.workspace import (
    CPU_DEVELOPMENT_PROFILE,
    DEVELOPMENT_PROFILES,
    GPU_DEVELOPMENT_PROFILE,
    HOME_ALIAS_ROOT,
    LEGACY_STORAGE_ROOT,
    WORKSPACE_COMPUTE_PATH,
    WORKSPACE_CONTAINER_PATH,
    WORKSPACE_DEFAULT_WORKDIR,
    WORKSPACE_LOGICAL_ROOT,
    WORKSPACE_MOUNT_CONTRACT_VERSION,
    WORKSPACE_QUOTA_BYTES,
    WORKSPACE_REQUIRED_DIRECTORIES,
    WORKSPACE_ROOT,
    WorkspaceBinding,
    WorkspaceLayout,
    legacy_storage_path,
    logical_workspace_path,
    profile_gpu_count,
    workspace_binding,
    workspace_path,
    workspace_relative_parts,
)

__all__ = [
    "CPU_DEVELOPMENT_PROFILE",
    "DEVELOPMENT_PROFILES",
    "GPU_DEVELOPMENT_PROFILE",
    "HOME_ALIAS_ROOT",
    "LEGACY_STORAGE_ROOT",
    "WORKSPACE_COMPUTE_PATH",
    "WORKSPACE_CONTAINER_PATH",
    "WORKSPACE_DEFAULT_WORKDIR",
    "WORKSPACE_LOGICAL_ROOT",
    "WORKSPACE_MOUNT_CONTRACT_VERSION",
    "WORKSPACE_QUOTA_BYTES",
    "WORKSPACE_REQUIRED_DIRECTORIES",
    "WORKSPACE_ROOT",
    "WorkspaceBinding",
    "WorkspaceLayout",
    "legacy_storage_path",
    "logical_workspace_path",
    "profile_gpu_count",
    "workspace_binding",
    "workspace_path",
    "workspace_relative_parts",
]
