[Service]
ExecStart=
ExecStart=/usr/local/bin/node_exporter --web.listen-address=127.0.0.1:9100 --web.telemetry-path=/metrics --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
ReadOnlyPaths=/var/lib/node_exporter/textfile_collector
