"""initial portal schema

Revision ID: dd26070f46bf
Revises:
Create Date: 2026-08-06 02:01:50.457929
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dd26070f46bf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_registry_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registry', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('safe_detail', sa.String(length=255), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry')
    )
    op.create_table('portal_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portal_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('portal_system_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_system_snapshots_snapshot_type'), 'portal_system_snapshots', ['snapshot_type'], unique=False)
    op.create_table('portal_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login_name', sa.String(length=64), nullable=False),
    sa.Column('normalized_login', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('unix_username', sa.String(length=32), nullable=True),
    sa.Column('account_state', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'LOCKED', 'DECOMMISSIONED', name='accountstate', native_enum=False, length=32), nullable=False),
    sa.Column('password_state', sa.Enum('SETUP_REQUIRED', 'SET', 'RESET_REQUIRED', 'DISABLED', name='passwordstate', native_enum=False, length=32), nullable=False),
    sa.Column('resource_onboarding_state', sa.Enum('NOT_ENROLLED', 'DRAFT', 'STAGED', 'READY_FOR_ACTIVATION', 'ACTIVE', 'SUSPENDED', 'FAILED', name='onboardingstate', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_login')
    )
    op.create_table('portal_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registry', sa.String(length=64), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('digest', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('imported_by', sa.Uuid(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry', 'repository', 'digest')
    )
    op.create_table('portal_managed_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portal_user_id', sa.Uuid(), nullable=False),
    sa.Column('unix_username', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('shell', sa.String(length=128), nullable=False),
    sa.Column('host_access_state', sa.String(length=32), nullable=False),
    sa.Column('gpu_isolation_state', sa.String(length=32), nullable=False),
    sa.Column('slurm_account', sa.String(length=64), nullable=True),
    sa.Column('slurm_qos', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('container_name', sa.String(length=128), nullable=True),
    sa.Column('container_port', sa.Integer(), nullable=True),
    sa.Column('onboarding_state', sa.Enum('NOT_ENROLLED', 'DRAFT', 'STAGED', 'READY_FOR_ACTIVATION', 'ACTIVE', 'SUSPENDED', 'FAILED', name='onboardingstate', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_name'),
    sa.UniqueConstraint('container_port'),
    sa.UniqueConstraint('portal_user_id'),
    sa.UniqueConstraint('project_id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('unix_username')
    )
    op.create_table('portal_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('request_summary', sa.String(length=500), nullable=False),
    sa.Column('validated_payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'ROLLING_BACK', 'ROLLED_BACK', 'CANCELLED', 'EXPIRED', name='operationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_execution_id', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.String(length=1000), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('rollback_status', sa.String(length=32), nullable=True),
    sa.Column('related_report', sa.String(length=255), nullable=True),
    sa.Column('related_git_commit', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requested_by', 'idempotency_key')
    )
    op.create_index(op.f('ix_portal_operations_operation_type'), 'portal_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_portal_operations_requested_by'), 'portal_operations', ['requested_by'], unique=False)
    op.create_table('portal_password_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('portal_password_setup_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_portal_password_setup_tokens_user_id'), 'portal_password_setup_tokens', ['user_id'], unique=False)
    op.create_table('portal_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reauthenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_index(op.f('ix_portal_sessions_user_id'), 'portal_sessions', ['user_id'], unique=False)
    op.create_table('portal_user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['portal_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('portal_audit_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent_digest', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('safe_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['portal_operations.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_timestamp', 'portal_audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_portal_audit_events_event_type'), 'portal_audit_events', ['event_type'], unique=False)
    op.create_table('portal_containers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('managed_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_digest', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('desired_state', sa.String(length=32), nullable=False),
    sa.Column('observed_state', sa.String(length=32), nullable=False),
    sa.Column('safe_spec', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_rebuilt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['managed_user_id'], ['portal_managed_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ssh_port')
    )
    op.create_table('portal_operation_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('safe_comment', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['portal_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_operation_approvals_operation_id'), 'portal_operation_approvals', ['operation_id'], unique=False)
    op.create_table('portal_operation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('safe_message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['portal_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_operation_events_operation_id'), 'portal_operation_events', ['operation_id'], unique=False)
    op.create_table('portal_ssh_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('managed_user_id', sa.Uuid(), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('comment_summary', sa.String(length=128), nullable=False),
    sa.Column('public_key_ciphertext', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['managed_user_id'], ['portal_managed_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_portal_ssh_keys_managed_user_id'), 'portal_ssh_keys', ['managed_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_ssh_keys_managed_user_id'), table_name='portal_ssh_keys')
    op.drop_table('portal_ssh_keys')
    op.drop_index(op.f('ix_portal_operation_events_operation_id'), table_name='portal_operation_events')
    op.drop_table('portal_operation_events')
    op.drop_index(op.f('ix_portal_operation_approvals_operation_id'), table_name='portal_operation_approvals')
    op.drop_table('portal_operation_approvals')
    op.drop_table('portal_containers')
    op.drop_index(op.f('ix_portal_audit_events_event_type'), table_name='portal_audit_events')
    op.drop_index('ix_audit_timestamp', table_name='portal_audit_events')
    op.drop_table('portal_audit_events')
    op.drop_table('portal_user_roles')
    op.drop_index(op.f('ix_portal_sessions_user_id'), table_name='portal_sessions')
    op.drop_table('portal_sessions')
    op.drop_index(op.f('ix_portal_password_setup_tokens_user_id'), table_name='portal_password_setup_tokens')
    op.drop_table('portal_password_setup_tokens')
    op.drop_table('portal_password_credentials')
    op.drop_index(op.f('ix_portal_operations_requested_by'), table_name='portal_operations')
    op.drop_index(op.f('ix_portal_operations_operation_type'), table_name='portal_operations')
    op.drop_table('portal_operations')
    op.drop_table('portal_managed_users')
    op.drop_table('portal_images')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_portal_system_snapshots_snapshot_type'), table_name='portal_system_snapshots')
    op.drop_table('portal_system_snapshots')
    op.drop_table('portal_settings')
    op.drop_table('portal_roles')
    op.drop_table('portal_registry_status')
    # ### end Alembic commands ###
